language: node_js
node_js:
- '0.12'
- '0.10'
before_install:
- openssl aes-256-cbc -K $encrypted_940d51811bdb_key -iv $encrypted_940d51811bdb_iv
  -in env-dev.ini.enc -out env-dev.ini -d
- npm install -g grunt-cli
